### ISSUE TITLE
Check if secret exists before trying to access or manipulate it

### ISSUE THREAD

**Issue by anx-mwutte** [rway7/secure-eloquent#1]
Hi, I think it would be suggestive to check if the array index is set in the secure() and unsecure() function before trying to manipulate it. Otherwise there wil be errors, if not all model fields are updated at once.

Instead of:
```
foreach ($this->secrets ?: [] as $secret) {
    $this->attributes[$secret] = $this->encrypter($key)->encryptString($this->attributes[$secret]);
}
```

it would be better to do so:
```
foreach ($this->secrets ?: [] as $secret) {
    if( isset( $this->attributes[$secret] ) ){
        $this->attributes[$secret] = $this->encrypter($key)->encryptString($this->attributes[$secret]);
    }
}
```

So it doesn't mind whether a specific model attribute is set or not.

**Comment by rway7** [comment]
Sorry for reply this late. Yes, it would be better if to only encrypt the exists attributes. It has just been fixed. Thanks for this suggestion!
